# 系统名称
System: FSM-Simulator
# 版本号
Version: V1
# FSM系统大小 单位MB
DiskSize: 1024
# 系统位数
bit: 64
# 数据块大小 单位KB
DataBlockSize: 8
# 数据块索引大小 单位KB
DataBlockIndexSize: 4
# 数据块数量
DataBlockNum: 120000
# inode大小 单位KB
InodeSize: 128
# inode密度
InodeDensity: 2048